 var MSG = {
    title: "mxc-parsec",
    blocks: "Blocks",
    linkTooltip: "Save and link to blocks.",
    runTooltip: "Run the program defined by the blocks in the workspace.",
    badCode: "Program error:\n%1",
    timeout: "Maximum execution iterations exceeded.",
    trashTooltip: "Discard all blocks.",
    listVariable: "list",
    textVariable: "text",
    httpRequestError: "There was a problem with the request.",
    linkAlert: "Share your blocks with this link:\n\n%1",
    hashError: "Sorry, '%1' doesn't correspond with any saved program.",
    xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
    badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",

    //----------------------------------------------------
    // parsec category colours
    catAuxiliary: "Auxiliary Parsers",
    catBinary: "Binary Parsers",
    catBoolean: "Boolean Parsers",
    catString: "Strings & Keywords",
    catChar: "Single Characters",
    catInteger: "Number Parsers",
    catDirective: "Parser Directives",
    catCast: "Attribute Casting",
    catPredicate: "Logic & Tests",
    catRule: "Rules & Grammars",
    catSkipper: "Skipping Control",
    catLoops: "Flow & Loops",
    //----------------------------------------------------
    // parsec category colours
    catRuleHue: "350",
    catDirectiveHue: "225",
    catLoopsHue: "215",
    catPredicateHue: "205",
    catSkipperHue: "195",
    catStringHue: "170",
    catCharHue: "160",
    catBooleanHue: "145",
    catIntegerHue: "135",
    catCastHue: "125",
    catBinaryHue: "60",
    catAuxiliaryHue: "45",

    //----------------------------------------------------
    // parsec block help urls
    blockAllNullHelpUrl: "http://www.maxence.de",
    blockAlnumHelpUrl: "http://www.maxence.de",
    blockAlphaHelpUrl: "http://www.maxence.de",
    blockAlternativeHelpUrl: "http://www.maxence.de",
    blockAndHelpUrl: "http://www.maxence.de",
    blockAsStringHelpUrl: "http://www.maxence.de",
    blockAttrHelpUrl: "http://www.maxence.de",
    blockBigEndianHelpUrl:"http://www.maxence.de",
    blockBinDoubleHelpUrl: "http://www.maxence.de",
    blockBinFloatHelpUrl: "http://www.maxence.de",
    blockBinHelpUrl: "http://www.maxence.de",
    blockBlankHelpUrl: "http://www.maxence.de",
    blockBoolHelpUrl: "http://www.maxence.de",
    blockByteHelpUrl: "http://www.maxence.de",
    blockCharHelpUrl: "http://www.maxence.de",
    blockCharRangeHelpUrl: "http://www.maxence.de",
    blockCharSetHelpUrl: "http://www.maxence.de",
    blockCntrlHelpUrl: "http://www.maxence.de",
    blockDifferenceHelpUrl: "http://www.maxence.de",
    blockDigitHelpUrl: "http://www.maxence.de",
    blockDoubleHelpUrl: "http://www.maxence.de",
    blockDwordHelpUrl: "http://www.maxence.de",
    blockEoiHelpUrl: "http://www.maxence.de",
    blockEolHelpUrl: "http://www.maxence.de",
    blockEpsHelpUrl: "http://www.maxence.de",
    blockExpectDHelpUrl: "http://www.maxence.de",
    blockExpectHelpUrl: "http://www.maxence.de",
    blockFalseHelpUrl: "http://www.maxence.de",
    blockFloatHelpUrl: "http://www.maxence.de",
    blockGrammarHelpUrl: "http://www.maxence.de",
    blockGraphHelpUrl: "http://www.maxence.de",
    blockHexHelpUrl: "http://www.maxence.de",
    blockHoldHelpUrl: "http://www.maxence.de",
    blockIntHelpUrl: "http://www.maxence.de",
    blockKleeneHelpUrl: "http://www.maxence.de",
    blockLazyHelpUrl: "http://www.maxence.de",
    blockListHelpUrl: "http://www.maxence.de",
    blockLitHelpUrl: "http://www.maxence.de",
    blockLittleEndianHelpUrl:"http://www.maxence.de",
    blockLongDoubleHelpUrl: "http://www.maxence.de",
    blockLongHelpUrl: "http://www.maxence.de",
    blockLongLongHelpUrl: "http://www.maxence.de",
    blockLowerHelpUrl: "http://www.maxence.de",
    blockMatchesHelpUrl: "http://www.maxence.de",
    blockNativeEndianHelpUrl:"http://www.maxence.de",
    blockNoCaseHelpUrl: "http://www.maxence.de",
    blockNoSkipHelpUrl: "http://www.maxence.de",
    blockNotHelpUrl: "http://www.maxence.de",
    blockOctHelpUrl: "http://www.maxence.de",
    blockOmitHelpUrl: "http://www.maxence.de",
    blockOptionalHelpUrl: "http://www.maxence.de",
    blockPermutationHelpUrl: "http://www.maxence.de",
    blockPlusHelpUrl: "http://www.maxence.de",
    blockPrintHelpUrl: "http://www.maxence.de",
    blockPunctHelpUrl: "http://www.maxence.de",
    blockQwordHelpUrl: "http://www.maxence.de",
    blockRawHelpUrl: "http://www.maxence.de",
    blockRepeatHelpUrl: "http://www.maxence.de",
    blockRuleHelpUrl: "http://www.maxence.de",
    blockRulerefHelpUrl: "http://www.maxence.de",
    blockSequenceHelpUrl: "http://www.maxence.de",
    blockSequentialOrHelpUrl: "http://www.maxence.de",
    blockShortHelpUrl: "http://www.maxence.de",
    blockSkipHelpUrl: "http://www.maxence.de",
    blockSpaceHelpUrl: "http://www.maxence.de",
    blockStringHelpUrl: "http://www.maxence.de",
    blockSymbolsHelpUrl: "http://www.maxence.de",
    blockTrueHelpUrl: "http://www.maxence.de",
    blockUintHelpUrl: "http://www.maxence.de",
    blockUlongHelpUrl: "http://www.maxence.de",
    blockUlongLongHelpUrl: "http://www.maxence.de",
    blockUpperHelpUrl: "http://www.maxence.de",
    blockUshortHelpUrl: "http://www.maxence.de",
    blockWordHelpUrl: "http://www.maxence.de",
    blockXdigitHelpUrl: "http://www.maxence.de",

    //----------------------------------------------------
    // parsec block tooltips
    blockAdvanceTooltip: "advance tooltip",
    blockAllNullTooltip: "all_null tooltip",
    blockAlnumTooltip: "alnum tooltip",
    blockAlphaTooltip: "alpha tooltip",
    blockAlternativeTooltip: "alternative tooltip",
    blockAndTooltip: "and tooltip",
    blockAsStringTooltip: "as_string tooltip",
    blockAttrTooltip: "attr tooltip",
    blockBigEndianTooltip:" big endian tooltip",
    blockBinDoubleTooltip: "bin_double tooltip",
    blockBinFloatTooltip: "bin_float tooltip",
    blockBinTooltip: "bin tooltip",
    blockBlankTooltip: "blank tooltip",
    blockBoolTooltip: "bool tooltip",
    blockByteTooltip: "byte tooltip",
    blockCharTooltip: "char tooltip",
    blockCharRangeTooltip: "charrange tooltip",
    blockCharSetTooltip: "charset tooltip",
    blockCntrlTooltip: "cntrl tooltip",
    blockDifferenceTooltip: "difference tooltip",
    blockDigitTooltip: "digit tooltip",
    blockDoubleTooltip: "double tooltip",
    blockDwordTooltip: "dword tooltip",
    blockEoiTooltip: "eoi tooltip",
    blockEolTooltip: "eol tooltip",
    blockEpsTooltip: "eps tooltip",
    blockExpectTooltip: "expect tooltip",
    blockFalseTooltip: "false tooltip",
    blockFloatTooltip: "float tooltip",
    blockGrammarTooltip: "grammar tooltip",
    blockGraphTooltip: "graph tooltip",
    blockHexTooltip: "hex tooltip",
    blockHoldTooltip: "hold tooltip",
    blockIntTooltip: "int tooltip",
    blockKleeneTooltip: "kleene tooltip",
    blockLazyTooltip: "lazy tooltip",
    blockListTooltip: "list tooltip",
    blockLitTooltip: "lit tooltip",
    blockLittleEndianTooltip:" little endian tooltip",
    blockLongDoubleTooltip: "long_double tooltip",
    blockLongLongTooltip: "long_long tooltip",
    blockLongTooltip: "long tooltip",
    blockLowerTooltip: "lower tooltip",
    blockMatchesTooltip: "matches tooltip",
    blockNativeEndianTooltip:"native endian tooltip",
    blockNoCaseTooltip: "no_case tooltip",
    blockNoSkipTooltip: "no_skip tooltip",
    blockNotTooltip: "not tooltip",
    blockOctTooltip: "oct tooltip",
    blockOmitTooltip: "omit tooltip",
    blockOptionalTooltip: "optional tooltip",
    blockPermutationTooltip: "permutation tooltip",
    blockPlusTooltip: "plus tooltip",
    blockPrintTooltip: "print tooltip",
    blockPunctTooltip: "punct tooltip",
    blockQwordTooltip: "qword tooltip",
    blockRawTooltip: "raw tooltip",
    blockRepeatTooltip: "repeat tooltip",
    blockRuleTooltip: "rule tooltip",
    blockReferencefTooltip: "reference tooltip",
    blockSequenceTooltip: "sequence tooltip",
    blockSequentialOrTooltip: "sequential_or tooltip",
    blockShortTooltip: "short tooltip",
    blockSkipTooltip: "skip tooltip",
    blockSpaceTooltip: "space tooltip",
    blockStringTooltip: "string tooltip",
    blockSymbolsTooltip: "symbols tooltip",
    blockTrueTooltip: "true tooltip",
    blockUintTooltip: "uint tooltip",
    blockUlongLongTooltip: "ulong_long tooltip",
    blockUlongTooltip: "ulong tooltip",
    blockUpperTooltip: "upper tooltip",
    blockUshortTooltip: "ushort tooltip",
    blockWordTooltip: "word tooltip",
    blockXdigitTooltip: "xdigit tooltip",

    //----------------------------------------------------
    // parsec blocks
    blockAdvanceMsg1: "advance input iterator by",
    blockAllNullMsg1: "",
    blockAlternativeMsg1: "first succeeding alternative of",
    blockAndMsg1: "test success of",
    blockAsStringMsg1: "as string",
    blockAttrMsg1: "direct attribute",
    blockBigEndianMsg1: "(big endian byte order)",
    blockBinDoubleMsg1: "binary double",
    blockBinFloatMsg1: "binary float",
    blockBinMsg1: "binary number",
    blockBoolMsg1: "boolean",
    blockByteMsg1: "byte",
    blockCharMsg1: "character",
    blockCharRangeMsg1: "character range",
    blockCharRangeMsg2: "from",
    blockCharRangeMsg3: "to",
    blockCharSetMsg1: "character set",
    blockDifferenceMsg1: "accept",
    blockDoubleMsg1: "double",
    blockDwordMsg1: "double word",
    blockEoiMsg1: "end of input",
    blockEolMsg1: "end of line",
    blockEpsMsg1: "epsilon",
    blockExpectMsg1: "expect",
    blockFalseMsg1: "false",
//    blockCharNegateFalseMsg1:"any",
    blockFloatMsg1: "float",
    blockHexMsg1: "hexadecimal number",
    blockHoldMsg1: "hold",
    blockIntMsg1: "integer",
    blockKleeneStarMsg1: "zero or more of",
    blockLazyMsg1: "lazily do",
    blockListMsg1: "list of",
    blockLitMsg1: "literal",
    blockLittleEndianMsg1: "(little endian byte order)",
    blockLongDoubleMsg1: "long double",
    blockLongLongMsg1: "long long",
    blockLongMsg1: "long",
    blockMatchesMsg1: "matches",
    blockNativeEndianMsg1: "(machine native byte order)",
    blockNoCaseMsg1: "ignoring case get",
    blockNoSkipMsg1: "without skipping",
    blockLexemeMsg1: "without intermediate skipping",
    blockNotMsg1: "test failure of",
    blockOctMsg1: "octal number",
    blockOmitMsg1: "omit",
    blockOptionalMsg1: "optionally",
    blockPermutationMsg1: "permutation of",
    blockKleenePlusMsg1: "one or more of",
    blockQwordMsg1: "quad word",
    blockRawMsg1: "raw",
    blockRepeatMsg1: "repeat",
    blockRuleMsg1: "rule",
    blockReferenceMsg1: "reference",
    blockSequenceMsg1: "sequence of",
    blockSequentialOrMsg1: "sequential or",
    blockShortMsg1: "short",
    blockSkipMsg1: "with skipping enabled",
    blockSkipperMsg1: "with alternative skipper",
    blockSkipperMsg3: "read",
    blockStringMsg1: "string",
    blockSymbolsMsg1: "symbols",
    blockTrueMsg1: "true",
//    blockCharNegateTrueMsg1: "any character but",
    blockUintMsg1: "uint",
    blockUlongLongMsg1: "unsigned long long",
    blockUlongMsg1: "unsigned long",
    blockUshortMsg1: "unsigned short",
    blockWordMsg1: "word",
    blockXdigitMsg1: "hexadecimal digit",
    blockCharRangeMsg1: "character from range",
    blockCharRangeMsg2: "to",
    blockIntegerRangeInputMsg1: "from range",
    blockIntegerRangeInputMsg2: "to",
    blockIntegerDigitsInputMsg1: "with number of digits between",
    blockIntegerDigitsInputMsg2: "and",
    blockCharSetMsg1: "character from set",
    blockCharSingleInputMsg1:"",
    blockGrammarMsg1:"grammar",
    blockGrammarMsg2:"rules",
    blockGrammarMsg4:"start rule",
    blockRuleMsg2:"parser",
    blockListMsg3:"separated by",
    blockDifferenceMsg3:"but not",
    blockReferenceMsg2:"select rule",
    blockPreskipperMsg1:"and without pre-skipping",
    blockRepeatForeverMsg1:"forever",
    blockRepeatExactlyMsg1:"times",
    blockRepeatMinMsg1:"at least",
    blockRepeatMinMsg2:"times",
    blockRepeatMinMaxMsg1:"at least",
    blockRepeatMinMaxMsg2:"times",
    blockRepeatMinMaxMsg3:"but no more than",
    blockRepeatMinMaxMsg4:"times",
    blockCharAllMsg1:"any character",
    blockSignedIntegerMsg1:"signed integer",
    blockUnsignedIntegerMsg1:"unsigned integer",
    blockFloatingPointMsg1:"floating point number",
    blockCharClassMsg1:"character of class ",
    blockIntegerAllMsg1:"any",
    blockBinaryAllMsg1:"any",
    blockNegateMsg1:"any character but ...",

    // @todo: consider translatable char class dropbox
    blockAlnumMsg1: "letter or digit",
    blockAlphaMsg1: "letter",
    blockBlankMsg1: "space or tab",
    blockCntrlMsg1: "control character",
    blockDigitMsg1: "digit",
    blockGraphMsg1: "graphical character",
    blockLowerMsg1: "lowercase character",
    blockPrintMsg1: "printable character",
    blockPunctMsg1: "punctuation character",
    blockSpaceMsg1: "whitespace character",
    blockUpperMsg1: "uppercase character",
};
